run: 
	@echo "Running server"
	DB_READ_URL="postgres://postgres:password@localhost:55432/grpc-training" DB_WRITE_URL="postgres://postgres:password@localhost:55432/grpc-training" go run main.go

.PHONY: run